version: '3'

services:

    djangoproject:
        container_name: djangosite
        image: djangobase:latest
        build:
            context: .
            args:
                appname: app
                sitefqdn: "${HOSTNAME}"
        ports:
            - "8000:8000"
        volumes:
            - media:/django/project/media
            - static:/django/project/static

volumes:
    media:
    static:

## Raw:
#    docker-compose run --rm --name djangosite -v ${PWD}/project:/var/django/project -p 8000:8000 djangoproject djangocms \
#    --config-file /var/django/config.ini \
#    --db mysql://djangosite:djangositeSQLpassword@djangodata/djangosite \
#    -sp . app
