version: '3'

services:

    mysite:
        image: djangobase:base
        container_name: mysite
        ports:
            - "8000:8000"
        volumes:
            - $PWD:/usr/src/app

        build: .


